name: kirk
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - absl-py=2.1.0=py312haa95532_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py312h05f76fc_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py312h2bbff1b_0
  - arrow-cpp=16.1.0=h7cd61ee_0
  - async-lru=2.0.4=py312haa95532_0
  - aws-c-auth=0.6.19=h2bbff1b_0
  - aws-c-cal=0.5.20=h2bbff1b_0
  - aws-c-common=0.8.5=h2bbff1b_0
  - aws-c-compression=0.2.16=h2bbff1b_0
  - aws-c-event-stream=0.2.15=hd77b12b_0
  - aws-c-http=0.6.25=h2bbff1b_0
  - aws-c-io=0.13.10=h2bbff1b_0
  - aws-c-mqtt=0.7.13=h2bbff1b_0
  - aws-c-s3=0.1.51=h2bbff1b_0
  - aws-c-sdkutils=0.1.6=h2bbff1b_0
  - aws-checksums=0.1.13=h2bbff1b_0
  - aws-crt-cpp=0.18.16=hd77b12b_0
  - aws-sdk-cpp=1.10.55=hd77b12b_0
  - beautifulsoup4=4.13.4=py312haa95532_0
  - blas=1.0=mkl
  - boost-cpp=1.82.0=h59b6b97_2
  - bottleneck=1.3.7=py312he558020_0
  - brotli=1.0.9=h2bbff1b_8
  - brotli-bin=1.0.9=h2bbff1b_8
  - brotli-python=1.0.9=py312hd77b12b_8
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.19.1=h2bbff1b_0
  - ca-certificates=2025.7.14=h4c7d964_0
  - catalogue=2.0.10=py312h2e8e312_1
  - cffi=1.17.1=py312h827c3e9_0
  - cloudpathlib=0.21.1=pyhd8ed1ab_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=py312haa95532_0
  - confection=0.1.5=pyhecae5ae_0
  - cpython=3.12.11=py312hd8ed1ab_0
  - cuda-cccl=12.4.127=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-profiler-api=12.4.127=0
  - cuda-runtime=11.8.0=0
  - cuda-version=11.8=h70ddcb2_3
  - cudatoolkit=11.8.0=h09e9e62_13
  - cupy=13.5.1=py312he81c058_1
  - cupy-core=13.5.1=py312h5b11f8c_1
  - cymem=2.0.11=py312h275cf98_0
  - cython-blis=1.3.0=py312h1a27103_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=3.6.0=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.3.8=pyhd8ed1ab_0
  - et_xmlfile=1.1.0=py312haa95532_1
  - expat=2.6.3=h5da7b33_0
  - fastrlock=0.8.3=py312h4023b64_1
  - filelock=3.13.1=py312haa95532_0
  - freetype=2.12.1=ha860e81_0
  - frozenlist=1.7.0=py312hfdf67e6_0
  - gflags=2.2.2=hd77b12b_1
  - giflib=5.2.2=h7edc060_0
  - glog=0.5.0=hd77b12b_1
  - greenlet=3.0.1=py312hd77b12b_0
  - h11=0.14.0=py312haa95532_0
  - hf-xet=1.1.5=py39h17685eb_3
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.2=py312haa95532_0
  - httpx=0.27.0=py312haa95532_0
  - huggingface_hub=0.34.3=pyhd8ed1ab_0
  - icu=73.1=h6c2663c_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=py312haa95532_0
  - ipywidgets=8.1.5=pyhd8ed1ab_0
  - jpeg=9e=h827c3e9_3
  - jsonschema=4.23.0=py312haa95532_0
  - jupyter_core=5.7.2=py312haa95532_0
  - jupyterlab=4.0.11=py312haa95532_0
  - jupyterlab_server=2.27.3=py312haa95532_0
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_0
  - krb5=1.20.1=h5b6d351_0
  - langcodes=3.4.1=pyhd8ed1ab_1
  - language-data=1.3.0=pyhff2d567_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libabseil=20240116.2=cxx17_h5da7b33_0
  - libboost=1.82.0=h3399ecb_2
  - libbrotlicommon=1.0.9=h2bbff1b_8
  - libbrotlidec=1.0.9=h2bbff1b_8
  - libbrotlienc=1.0.9=h2bbff1b_8
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcurand=10.3.5.147=0
  - libcurand-dev=10.3.5.147=0
  - libcurl=8.9.1=h0416ee5_0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.17=h2bbff1b_1
  - libevent=2.1.12=h56d1f94_1
  - libexpat=2.6.3=he0c23c2_0
  - libffi=3.4.4=hd77b12b_1
  - libgrpc=1.62.2=hf25190f_0
  - libiconv=1.16=h2bbff1b_3
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.17=h906ac69_0
  - libprotobuf=4.25.3=hf2fb9eb_0
  - libsodium=1.0.18=h62dcd97_0
  - libsqlite=3.50.3=hf5d6505_1
  - libssh2=1.11.0=h291bd65_0
  - libthrift=0.15.0=h4364b78_2
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.5=h24da03e_0
  - libxslt=1.1.41=h0739af5_0
  - libzlib=1.2.13=h2466b09_6
  - lxml=5.3.0=py312h395c83e_0
  - lz4-c=1.9.4=h2bbff1b_1
  - marisa-trie=1.2.1=py312h275cf98_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py312h31fea79_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py312h2bbff1b_1
  - mkl_fft=1.3.10=py312h827c3e9_0
  - mkl_random=1.2.7=py312h0158946_0
  - mpmath=1.3.0=py312haa95532_0
  - multidict=6.6.3=py312h05f76fc_0
  - multiprocess=0.70.16=py312h4389bb4_1
  - murmurhash=1.0.10=py312h275cf98_2
  - nbformat=5.10.4=py312haa95532_0
  - nest-asyncio=1.6.0=py312haa95532_0
  - networkx=3.2.1=py312haa95532_0
  - notebook=7.0.8=py312haa95532_2
  - numexpr=2.10.1=py312h4cd664f_0
  - numpy=1.26.4=py312hfd52020_0
  - numpy-base=1.26.4=py312h4dde369_0
  - openjpeg=2.5.2=hae555c5_0
  - openpyxl=3.1.5=py312h827c3e9_0
  - openssl=3.5.1=h725018a_0
  - orc=2.0.1=hd8d391b_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.2=py312h0158946_0
  - ply=3.11=py312haa95532_1
  - preshed=3.0.9=py312h275cf98_2
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - propcache=0.3.1=py312h31fea79_0
  - pyarrow=16.1.0=py312h0158946_0
  - pydantic-core=2.33.2=py312h8422cdd_0
  - pyqt=5.15.10=py312hd77b12b_0
  - pyqt5-sip=12.13.0=py312h2bbff1b_0
  - pysocks=1.7.1=py312haa95532_0
  - python=3.12.3=h2628c8c_0_cpython
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-gil=3.12.11=hd8ed1ab_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py312h4389bb4_2
  - python_abi=3.12=8_cp312
  - pytorch=2.5.0=py3.12_cuda11.8_cudnn9_0
  - pytorch-cuda=11.8=h24eeafa_6
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py312haa95532_0
  - pyyaml=6.0.2=py312h827c3e9_0
  - qt-main=5.15.2=h19c9488_10
  - re2=2022.04.01=hd77b12b_0
  - regex=2024.11.6=py312h4389bb4_0
  - requests=2.32.3=py312haa95532_0
  - rfc3339-validator=0.1.4=py312haa95532_0
  - rfc3986-validator=0.1.1=py312haa95532_0
  - rich=13.9.4=pyhd8ed1ab_1
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - setuptools=72.1.0=py312haa95532_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - sip=6.7.12=py312hd77b12b_0
  - six=1.17.0=pyhe01879c_1
  - smart-open=7.3.0.post1=h87fe6b5_0
  - smart_open=7.3.0.post1=pyhe01879c_0
  - snappy=1.2.1=hcdb6601_0
  - spacy=3.8.7=py312he3e9d37_0
  - spacy-alignments=0.9.2=py312h362b069_0
  - spacy-legacy=3.0.12=pyhd8ed1ab_0
  - spacy-loggers=1.0.5=pyhd8ed1ab_0
  - sqlalchemy=2.0.34=py312h54f65d0_0
  - sqlite=3.45.3=h2bbff1b_0
  - srsly=2.5.1=py312h275cf98_1
  - tbb=2021.8.0=h59b6b97_0
  - thinc=8.3.6=py312h9b46583_0
  - tk=8.6.14=h0416ee5_0
  - tokenizers=0.13.3=py312h49fca51_0
  - tqdm=4.66.5=py312hfc267ef_0
  - traitlets=5.14.3=py312haa95532_0
  - transformers=4.24.0=pyhd8ed1ab_0
  - typer=0.16.0=pyh167b9f4_0
  - typer-slim=0.16.0=pyhe01879c_0
  - typer-slim-standard=0.16.0=hf964461_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2024b=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_1
  - ujson=5.10.0=py312h275cf98_1
  - unicodedata2=15.1.0=py312h2bbff1b_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.40=h2eaa2aa_1
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - vs2015_runtime=14.44.35208=h38c0c73_31
  - wasabi=1.1.3=pyhd8ed1ab_1
  - weasel=0.4.1=pyhd8ed1ab_2
  - webencodings=0.5.1=py312haa95532_2
  - websocket-client=1.8.0=py312haa95532_0
  - wheel=0.44.0=py312haa95532_0
  - widgetsnbextension=4.0.13=pyhd8ed1ab_0
  - wikipedia=1.4.0=pyhd8ed1ab_3
  - win_inet_pton=1.1.0=py312haa95532_0
  - winpty=0.4.3=4
  - xxhash=0.8.3=hbba6f48_0
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - yarl=1.20.1=py312h31fea79_0
  - zeromq=4.3.5=hd77b12b_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h2466b09_6
  - zstd=1.5.6=h8880b57_0
  - pip:
      - airbyte==0.20.0
      - airbyte-api==0.49.4
      - airbyte-cdk==5.17.0
      - airbyte-protocol-models-dataclasses==0.13.1
      - airbyte-protocol-models-pdv2==0.13.1
      - anyio==4.8.0
      - argon2-cffi==23.1.0
      - arrow==1.3.0
      - asn1crypto==1.5.1
      - asttokens==3.0.0
      - attributes-doc==0.4.0
      - attrs==24.3.0
      - babel==2.16.0
      - backoff==2.2.1
      - bleach==6.2.0
      - bracex==2.5.post1
      - cachetools==5.5.0
      - calamancy==0.2.2
      - cattrs==24.1.2
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - click==8.1.7
      - comm==0.2.2
      - contourpy==1.3.3
      - cryptography==42.0.8
      - curated-tokenizers==0.0.9
      - curated-transformers==0.1.1
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - debugpy==1.8.11
      - deprecated==1.2.15
      - dpath==2.2.0
      - duckdb==1.1.3
      - duckdb-engine==0.13.5
      - en-core-web-md==3.8.0
      - en-core-web-sm==3.8.0
      - en-core-web-trf==3.8.0
      - executing==2.1.0
      - fastjsonschema==2.21.1
      - fonttools==4.59.1
      - fqdn==1.5.1
      - fsspec==2023.12.2
      - genson==1.2.2
      - google-api-core==2.23.0
      - google-auth==2.36.0
      - google-cloud-bigquery==3.27.0
      - google-cloud-bigquery-storage==2.27.0
      - google-cloud-core==2.4.1
      - google-cloud-secret-manager==2.21.1
      - google-crc32c==1.6.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.66.0
      - grpc-google-iam-v1==0.13.1
      - grpcio==1.68.0
      - grpcio-status==1.68.0
      - ipython==8.31.0
      - isodate==0.6.1
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.5
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpatch==1.33
      - jsonpath-python==1.0.6
      - jsonpointer==3.0.0
      - jsonref==0.2
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-events==0.11.0
      - jupyter-http-over-ws==0.0.8
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.9
      - langchain-core==0.1.42
      - langsmith==0.1.143
      - markdown==3.7
      - marshmallow==3.23.1
      - matplotlib==3.10.5
      - matplotlib-inline==0.1.7
      - mistune==3.1.0
      - mmhash3==3.0.1
      - mypy-extensions==1.0.0
      - nbclient==0.10.2
      - nbconvert==7.16.5
      - nltk==3.8.1
      - notebook-shim==0.2.4
      - orjson==3.10.11
      - overrides==7.7.0
      - pandoc==2.4
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pendulum==2.0.3
      - pillow==11.3.0
      - pip==25.2
      - plac==1.4.5
      - platformdirs==4.3.6
      - plumbum==1.9.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.48
      - proto-plus==1.25.0
      - protobuf==5.28.3
      - psutil==6.1.1
      - psycopg==3.2.3
      - psycopg-binary==3.2.3
      - psycopg-pool==3.2.4
      - psycopg2-binary==2.9.10
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pydantic==2.9.2
      - pygments==2.19.1
      - pyiceberg==0.6.1
      - pyjwt==2.9.0
      - pyopenssl==24.2.1
      - pyparsing==3.2.3
      - pyrate-limiter==3.1.1
      - pyrsistent==0.20.0
      - python-crfsuite==0.9.11
      - python-dotenv==1.0.1
      - python-json-logger==3.2.1
      - python-ulid==2.7.0
      - pytorch-crf==0.7.2
      - pytzdata==2020.1
      - pywin32==308
      - pywinpty==2.0.14
      - pyzmq==26.2.0
      - referencing==0.35.1
      - requests-cache==1.2.1
      - requests-toolbelt==1.0.0
      - rpds-py==0.22.3
      - rsa==4.9
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - serpyco-rs==1.11.0
      - sklearn-crfsuite==0.5.0
      - sniffio==1.3.1
      - snowflake-connector-python==3.12.3
      - snowflake-sqlalchemy==1.6.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - spacy-crfsuite==1.7.0
      - spacy-curated-transformers==0.3.1
      - spacy-llm==0.7.3
      - spacy-lookups-data==1.0.5
      - spacy-transformers==1.3.5
      - sqlalchemy-bigquery==1.11.0
      - stack-data==0.6.3
      - strictyaml==1.7.3
      - structlog==24.4.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==8.5.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - time-machine==2.16.0
      - tinycss2==1.4.0
      - tl-calamancy-lg==0.2.0
      - tl-calamancy-md==0.1.0
      - tl-calamancy-trf==0.2.0
      - tomlkit==0.13.2
      - torchaudio==2.5.0
      - torchinfo==1.8.0
      - torchvision==0.20.0
      - tornado==6.4.2
      - types-python-dateutil==2.9.0.20241206
      - types-pyyaml==6.0.12.20240917
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - uri-template==1.3.0
      - url-normalize==1.4.3
      - urllib3==2.3.0
      - uuid7==0.1.0
      - wcmatch==8.4
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - werkzeug==3.0.6
      - wrapt==1.16.0
      - xmltodict==0.13.0
prefix: D:\Anaconda\envs\kirk
